In [ ]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [ ]:
# get dataframe info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [ ]:
#dropping stab column
df=df.drop('stab',axis=1)
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

In [ ]:
# check for null values
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [ ]:
# get training datasets
x = df.drop(columns=['stabf'],axis=1)
y = df['stabf']

In [ ]:
# split dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [ ]:
#standard scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain_scaled=pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
xtest_scaled=pd.DataFrame(scaler.transform(x_test), columns=x_test.columns)

In [ ]:
recall=82/(82+18)
fpr=2/(98+2)
total_price=5*2+18
recall,fpr,total_price

(0.82, 0.02, 28)

In [ ]:
recall=79/(79+21)
fpr=1/(99+1)
total_price=5*1+21
recall,fpr,total_price

(0.79, 0.01, 26)

In [ ]:
recall=90/(90+10)
fpr=4/(96+4)
total_price=5*4+10
recall,fpr,total_price

(0.9, 0.04, 30)

In [ ]:
recall=78/(78+22)
fpr=9/(91+9)
total_price=5*9+22
recall,fpr,total_price

(0.78, 0.09, 67)

In [ ]:
TP=255
FP=1380
FN=45
TN=20
Precision=TP/(TP+FP)
Recall=TP/(TP+FN)
F1=2*((Precision*Recall)/(Precision+Recall))
round(F1,4)

0.2636

In [ ]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier(random_state=1)
Rf.fit(xtrain_scaled,y_train)
y_pred=pd.Series(Rf.predict(xtest_scaled))

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
def score_data(y_test,y_pred, Rf):
  print(Rf)
  print(confusion_matrix(y_test,y_pred))
  print(classification_report(y_test,y_pred))
  print("Accuracy Score is: ", accuracy_score(y_test, y_pred))

In [ ]:
score_data(y_test, y_pred,'RandomForest Classifier')

RandomForest Classifier
[[ 625   87]
 [  55 1233]]
              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.929


In [ ]:
#XGB Classifier
from xgboost import XGBClassifier
xgb=XGBClassifier(random_state=1)
xgb.fit(xtrain_scaled,y_train)
y_pred=xgb.predict(xtest_scaled)
score_data(y_test, y_pred,'XGBClassifier')

XGBClassifier
[[ 603  109]
 [  52 1236]]
              precision    recall  f1-score   support

      stable       0.92      0.85      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000

Accuracy Score is:  0.9195


In [ ]:
#LGBM Classifier
from lightgbm import LGBMClassifier
lgbm= LGBMClassifier(random_state=1)
lgbm.fit(xtrain_scaled,y_train)
y_pred=lgbm.predict(xtest_scaled)
score_data(y_test, y_pred,'LGBM Classifier')

LGBM Classifier
[[ 635   77]
 [  48 1240]]
              precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

Accuracy Score is:  0.9375


In [ ]:
#ExtraTreesClassifier
from sklearn.ensemble import ExtraTreesClassifier
ext=ExtraTreesClassifier(random_state=1)
ext.fit(xtrain_scaled,y_train)
y_pred=ext.predict(xtest_scaled)
score_data(y_test, y_pred, 'ExtraTreesClassifier')

ExtraTreesClassifier
[[ 606  106]
 [  38 1250]]
              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.928


In [ ]:
#Hypertuning ExtraTrees Classifier

n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,'min_samples_leaf': min_samples_leaf,'min_samples_split': min_samples_split,'max_features': max_features}
from sklearn.model_selection import RandomizedSearchCV
ext=ExtraTreesClassifier()
rdm = RandomizedSearchCV(ext, param_distributions = hyperparameter_grid, cv=5, n_iter=10, n_jobs=-1, verbose=1, random_state=1, scoring='accuracy')
rdm.fit(xtrain_scaled, y_train)
rdm.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [ ]:
#ExtraTreesClassifier Optimal
ext_opt=ExtraTreesClassifier(random_state=1,max_features=None,min_samples_leaf=8,min_samples_split=2,n_estimators=1000)
ext_opt.fit(xtrain_scaled, y_train)
y_pred=ext_opt.predict(xtest_scaled)
score_data(y_test, y_pred,'ExtraTreesClassifier Optimal')

ExtraTreesClassifier Optimal
[[ 619   93]
 [  53 1235]]
              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.927


In [ ]:
#ExtraTreesClassifier Optimal
ext_opt=ExtraTreesClassifier(random_state=1,max_features='log2',min_samples_leaf=8,min_samples_split=2,n_estimators=500)
ext_opt.fit(xtrain_scaled, y_train)
y_pred=ext_opt.predict(xtest_scaled)
score_data(y_test, y_pred,'ExtraTreesClassifier Optimal')

ExtraTreesClassifier Optimal
[[ 545  167]
 [  14 1274]]
              precision    recall  f1-score   support

      stable       0.97      0.77      0.86       712
    unstable       0.88      0.99      0.93      1288

    accuracy                           0.91      2000
   macro avg       0.93      0.88      0.90      2000
weighted avg       0.92      0.91      0.91      2000

Accuracy Score is:  0.9095


In [ ]:
#ExtraTreesClassifier Optimal
ext_opt=ExtraTreesClassifier(random_state=1,max_features='auto',min_samples_leaf=6,min_samples_split=5,n_estimators=300)
ext_opt.fit(xtrain_scaled, y_train)
y_pred=ext_opt.predict(xtest_scaled)
score_data(y_test, y_pred,'ExtraTreesClassifier Optimal')

ExtraTreesClassifier Optimal
[[ 567  145]
 [  13 1275]]
              precision    recall  f1-score   support

      stable       0.98      0.80      0.88       712
    unstable       0.90      0.99      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.94      0.89      0.91      2000
weighted avg       0.93      0.92      0.92      2000

Accuracy Score is:  0.921


In [ ]:
#ExtraTreesClassifier Optimal
ext_opt=ExtraTreesClassifier(random_state=1,max_features=None,min_samples_leaf=4,min_samples_split=7,n_estimators=100)
ext_opt.fit(xtrain_scaled, y_train)
y_pred=ext_opt.predict(xtest_scaled)
score_data(y_test, y_pred,'ExtraTreesClassifier Optimal')

ExtraTreesClassifier Optimal
[[ 622   90]
 [  51 1237]]
              precision    recall  f1-score   support

      stable       0.92      0.87      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.9295


In [ ]:
#Feature Importances for ExtraTreesClassifier Optimal
feature_imp=ext_opt.feature_importances_
ext_optf=pd.DataFrame(feature_imp, index=xtrain_scaled.columns, columns=['Importance'])
print("Max Importance is of: ", ext_optf[['Importance']].idxmax())
print("Min Importance is of: ", ext_optf[['Importance']].idxmin())

Max Importance is of:  Importance    tau2
dtype: object
Min Importance is of:  Importance    p1
dtype: object
